# Maintenance banner container
#
# Create self-signed certs:  openssl req -x509 -newkey rsa:2048 -keyout nginx.key -out nginx.crt -sha256 -days 3650
# kubectl create secret generic nginx-generic-tls --from-file=./nginx.crt --from-file=./nginx.key --namespace maintenance
# kubectl create configmap maintenance-configmap --from-file=default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: maintenance
  namespace: maintenance
  labels:
    app: maintenance
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: maintenance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
  namespace: maintenance
  labels:
    app: maintenance
spec:
  selector:
    matchLabels:
      app: maintenance
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: maintenance
    spec:
      volumes:
      - name: secret-volume
        secret:
           secretName: nginx-generic-tls
      - name: configmap-volume
        configMap:
          name: maintenance-configmap 
      containers:
      - name: maintenance
        image: mtlucas/maintenance:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 30
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
      restartPolicy: Always
